service:
  name: spiders-node
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
  bye:
    handler: src/bye.test
    events:
      - http:
          method: get
          path: hello
  msg:
    handler: src/msg.message
    events:
      - http:
          method: get
          path: hello      
  players:
    handler: src/players.message
    events:
      - http:
          method: get
          path: hello 
  teams:
    handler: src/teams.message
    events:
      - http:
          method: get
          path: hello 